name: pipeline

on: [push, pull_request]

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        uses: haskell-actions/run-ormolu@v14

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.6.1"

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["lib/", "test/"]'
          fail-on: warning

  cabal:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        ghc: ["9.2", "9.4", "9.6", "9.8"]
        cabal: ["3.10"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haskell
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          cabal-update: true

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      - name: Save cached dependencies
        uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Test
        run: cabal test all

      - name: Check cabal file
        run: cabal check
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    needs: checks
    strategy:
      matrix:
        stack: ["2.11.1"]
        ghc: ["9.4.8"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haskell
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: |
          stack build --system-ghc --test --no-run-tests

      - name: Test
        run: |
          stack test --system-ghc
